version: "3.9"

services:
  app:
    image: danielcavalcante/minio-chunked-upload-download
    build:
      dockerfile: Dockerfile
    container_name: flask-app-prod
    restart: unless-stopped
    ports:
      - 80:5000
    networks:
      - minio_chunked_network
    environment:
      - MINIO_HOSTNAME=minio-server
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:-minioadmin}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY:-minioadmin}
      - MINIO_IS_SECURE=false
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    depends_on:
      - minio
    command: ["gunicorn", "-w", "2", "-b", "0.0.0.0:5000", "app:create_app()"]

  minio:
    image: minio/minio
    container_name: minio-server
    restart: unless-stopped
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"
    volumes:
      - storage-data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY:-minioadmin}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - minio_chunked_network

networks:
  minio_chunked_network:
    name: minio_chunked_network

volumes:
  storage-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ./data


